apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaving-net-dm
  namespace: weaving-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weaving-net
  template:
    metadata:
      name: weaving-net-pod
      labels:
        app: weaving-net
    spec:
      containers:
        - name: weaving-net
          image: /weaving-net/weaving-net:latest
          # If using a local image, use Never, default is Always
          #imagePullPolicy: Never
          command: ["./weaving_net", "-c", "/app/configs/weaving_net.yml"]
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          volumeMounts:
            - name: weaving-net-vl
              mountPath: /app/configs/
              readOnly: true

          ports:
            - name: http-port
              containerPort: 8080
          readinessProbe:
            httpGet:
              port: http-port
              path: /health
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: http-port
              path: /health

            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      # todo for private repositories, you need to create a secret (here docker-auth-secret) to store the account and password to log into docker
      imagePullSecrets:
        - name: docker-auth-secret
      volumes:
        - name: weaving-net-vl
          configMap:
            name: weaving-net-config
